### ISSUE TITLE
GDA 2 task list

### ISSUE THREAD

**Issue by borbware** [borbware/unity-basics-course#9]
- [ ] 3d animation import
- [ ] shaders
- [ ] small project: koirapeli
- [ ] small project: platformer toolkit
- [ ] cinemachine 3d camera
- [ ] 2D. rigidbodyn liikuttaminen seinän suuntasesti
